name: "Mirror Repo Action."
description: "Mirror the organization repos between hub (github/gitee)."
author: "kuxia"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  src_repo_url:
    description: 'SSH URL of the source repo.'
    required: true
    default: ''
  src_repo_branch:
    description: "Branch name to sync from."
    default: 'refs/remotes/origin/*'
  src_repo_tag:
    description: "Tag name to sync from."
    default: 'refs/tags/*'
  dst_repo_url:
    description: 'SSH URL of the destination repo.'
    required: true
    default: ''
  dst_repo_branch:
    description: "Branch name to sync to."
    default: 'refs/heads/*'
  dst_repo_tag:
    description: "Tag name to sync to."
    default: 'refs/tags/*'
  cache_path:
    description: "The path to cache the source repos code."
    default: '/github/workspace/mirror-repo-cache'
  errexit_flag:
    description: "Exit immediately if a simple command exits with a non-zero status, must be true or false. (use 'set -e', equivalent to 'set -o errexit')"
    default: true
  xtrace_debug:
    description: "Enable DEBUG for the script, must be true or false. (use 'set -x', equivalent to 'set -o xtrace')"
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src_repo_url }}
    - ${{ inputs.src_repo_branch }}
    - ${{ inputs.src_repo_tag }}
    - ${{ inputs.dst_repo_url }}
    - ${{ inputs.dst_repo_branch }}
    - ${{ inputs.dst_repo_tag }}
    - ${{ inputs.cache_path }}
    - ${{ inputs.errexit_flag }}
    - ${{ inputs.xtrace_debug }}