name: "Mirror Repo Action."
description: "Mirror the organization repos between hub (github/gitee)."
author: "kuxia"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  src_repo_url:
    description: 'SSH URL of the source repo.'
    required: true
    default: ''
  dst_repo_url:
    description: 'SSH URL of the destination repo.'
    required: true
    default: ''
  create_dst_repo_nonexist:
    description: "If destination repo does not exist, force to create it. must be true or false."
    default: false
  cache_path:
    description: "The path to cache the source repos code."
    default: '/github/workspace/mirror-repo-cache'
  request_tool:
    description: "Tool for checking the existence of url for hub, must be git or curl."
    default: 'git'
  errexit_flag:
    description: "Exit immediately if a simple command exits with a non-zero status, must be true or false. (use 'set -e', equivalent to 'set -o errexit')"
    default: true
  xtrace_debug:
    description: "Enable DEBUG for the script, must be true or false. (use 'set -x', equivalent to 'set -o xtrace')"
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src_repo_url }}
    - ${{ inputs.dst_repo_url }}
    - ${{ inputs.create_dst_repo_nonexist}}
    - ${{ inputs.cache_path }}
    - ${{ inputs.request_tool }}
    - ${{ inputs.errexit_flag }}
    - ${{ inputs.xtrace_debug }}