name: "Mirror Repo Action."
description: "Mirror the organization repos between hub (github/gitee)."
author: "kuxia"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  ssh_private_key:
    description: "The private SSH key which is used to to push code in destination hub."
    required: true
  source_repo:
    description: 'SSH URL of the source repo.'
    required: true
    default: ''
  destination_repo:
    description: 'SSH URL of the destination repo.'
    required: true
    default: ''
  force_creat_destination_repo:
    description: "If destination repo does not exist, force to create it."
    default: false
  cache_path:
    description: "The path to cache the source repos code."
    default: '/github/workspace/mirror-repo-cache'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.source_repo }}
    - ${{ inputs.destination_repo }}
    - ${{ inputs.force_creat_destination_repo}}
    - ${{ inputs.cache_path }}