name: "Mirror Repo Action."
description: "Mirror the organization repos between hub (github/gitee)."
author: "kuxia"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  src_repo_url:
    description: 'SSH URL of the source repo.'
    required: true
    default: ''
  dst_repo_url:
    description: 'SSH URL of the destination repo.'
    required: true
    default: ''
  force_creat_dst_repo:
    description: "If destination repo does not exist, force to create it."
    default: false
  cache_path:
    description: "The path to cache the source repos code."
    default: '/github/workspace/mirror-repo-cache'
  err_exit_flag:
    description: "Exit immediately if a simple command exits with a non-zero status. (use 'set -e')"
    required: true
  debug_flag:
    description: "Enable DEBUG for the script. (use 'set -x')"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src_repo_url }}
    - ${{ inputs.dst_repo_url }}
    - ${{ inputs.force_creat_dst_repo}}
    - ${{ inputs.cache_path }}
    - ${{ inputs.err_exit_flag }}
    - ${{ inputs.debug_flag }}