name: Test wei/git-sync action

on:
  # push推送时触发
  push:
    branches: [ main ]
    # 匹配到该路径的文件有push时触发
    paths:
      # .github/workflows/ 目录下的文件有推送提交时，工作流触发
      #- '.github/workflows/**'
      # 只有当本文件有推送提交时，才工作流触发
      - '.github/workflows/git-sync-action-test.yml'
      #- 'action.yml'
      #- 'Dockerfile'
      #- 'entrypoint.sh'
    # paths-ignore 表示该路径的文件有push时忽略触发。这里使用上面的 paths 来设置更符合我的要求(只有当本文件有推送提交时，该工作流触发 )。
    # paths-ignore:
    #   - 'docs/**'
    #   - 'README.md'
  # 定时任务触发
  schedule:
    # 每天北京时间9点跑
    # Runs at 04:00 UTC (12:00 AM Beijing) every day
    - cron:  '0 3 * * *'

jobs:
  run:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Github to Gitee with wei/git-sync
        uses: wei/git-sync@v2
        with:
          # 需要被同步的源端仓库
          source_repo: "git@github.com:microsoft/vscode-dev-containers.git"
          source_branch: "refs/remotes/source/*"
          # 需要同步到的目的仓库
          destination_repo: "git@gitee.com:kuxiade/vscode-dev-containers.git"
          destination_branch: "refs/heads/*"
          # 用于目的端上传代码的SSH key，用于从gituhb虚拟机上传代码到目的端仓库。
          ssh_private_key: ${{ secrets.GITEE_PRIVATE_SSH_KEY }}