name: Test mirror-repo-action

on:
  # push推送时触发
  push:
    branches: [ main ]
    # 匹配到该路径的文件有push时触发
    paths:
      # .github/workflows/ 目录下的文件有推送提交时，工作流触发
      #- '.github/workflows/**'
      # 只有当本文件有推送提交时，才工作流触发
      - '.github/workflows/mirror-repo-action-test.yml'
    # paths-ignore 表示该路径的文件有push时忽略触发。这里使用上面的 paths 来设置更符合我的要求(只有当本文件有推送提交时，该工作流触发 )。
    # paths-ignore:
    #   - 'docs/**'
    #   - 'README.md'
  # 定时任务触发
  schedule:
    # 每天北京时间9点跑
    # Runs at 04:00 UTC (12:00 AM Beijing) every day
    - cron:  '0 4 * * *'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee with mirror-repo-action
      uses: ./.
      env:
        # 用于目的端上传代码的SSH key，用于上传代码
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_SSH_KEY }}
      with:
        # 需要被同步的源端仓库
        source-repo: "git@github.com:wearerequired/git-mirror-action.git"
        # 需要同步到的目的仓库
        destination-repo: "git@gitee.com:kuxiade/git-mirror-action.git"